### ISSUE TITLE
Consider using active_attr

### ISSUE THREAD

**Issue by pda** [timcraft/formeze#3]
Have you considered delegating the attribute declaration and ActiveMode interface aspect to [active_attr](https://github.com/cgriego/active_attr), and focusing on building a thinner layer of form-specific support on top?

That's what I frequently do in an ad-hoc manner, it'd be nice to see a gem do it even better ;)

**Comment by timcraft** [comment]
@pda This gem isn't tied to ActiveRecord or ActiveModel (or Rails). The attribute declaration is delegated to attr_accessor, which is as simple as attribute declaration can possibly get--not sure why it would make sense to replace that with a coupler of heavy gem dependencies?

If you find yourself repeating the same pattern for building form objects on top of active_attr then maybe there is scope for adding additional functionality to active_attr, or publishing a different gem for that.

**Comment by pda** [comment]
Fair enough — I can see how you'd want to keep formeze self-contained, without any runtime dependencies.
